### ISSUE TITLE
ErrorException Undefined array key 1

### ISSUE THREAD

**Issue by hamransp** [monster010/codeigniter-vite-plugin#1]
I got an error after run : npm run build.
and when I access url project, it will display an error like this:

ErrorException
Undefined array key 1 

VENDORPATH\monster010\codeigniter-vite-plugin\src\Vite.php at line 136

![ci vitejs](https://github.com/monster010/codeigniter-vite-plugin/assets/35823221/47e6caa4-532e-4e22-9116-10629734946f)

**Comment by monster010** [comment]
Heyho,

thanks for the reporting, is fixed in release v0.0.6 =)
